# Generated by Django 5.1.1 on 2024-09-20 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='file_name',
        ),
    ]
