# Generated by Django 5.1.1 on 2024-09-26 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_imagepost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
