# Generated by Django 5.1.1 on 2024-09-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_imagepost_description_alter_imagepost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
