# Generated by Django 5.1.1 on 2024-10-08 23:39

import django.utils.timezone
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_remove_imagepost_pub_date_imagepost_created_date_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified date'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
